# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Email Daily Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Email daily report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Daily Report
          body: This is the daily report.
          to: